// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Gatsby = require("gatsby");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function make(to_, className, children) {
  return ReasonReact.wrapJsForReason(Gatsby.Link, {
              to: to_,
              className: className
            }, children);
}

var Link = /* module */[/* make */make];

exports.Link = Link;
/* gatsby Not a pure module */
