// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';


var Link = /* module */[];

var StaticQuery = /* module */[];

exports.Link = Link;
exports.StaticQuery = StaticQuery;
/* No side effect */
