// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Gatsby = require("gatsby");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function make(to_, className, children) {
  return ReasonReact.wrapJsForReason(Gatsby.Link, {
              to: to_,
              className: className
            }, children);
}

var Link = /* module */[/* make */make];

function make$1(query, children) {
  return ReasonReact.wrapJsForReason(Gatsby.StaticQuery, {
              query: query
            }, children);
}

var StaticQuery = /* module */[/* make */make$1];

exports.Link = Link;
exports.StaticQuery = StaticQuery;
/* gatsby Not a pure module */
