// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Gatsby = require("gatsby");
var Utils$ReactTemplate = require("./Utils.bs.js");

function str(prim) {
  return prim;
}

var article = Css.style(/* :: */[
      Css.marginBottom(Css.px(32)),
      /* [] */0
    ]);

var link = Css.style(/* :: */[
      Css.textDecoration(/* none */-922086728),
      /* :: */[
        Css.hover(/* :: */[
              Css.textDecoration(/* underline */131142924),
              /* :: */[
                Css.textDecorationColor(Css.red),
                /* [] */0
              ]
            ]),
        /* [] */0
      ]
    ]);

var h2 = Css.style(/* :: */[
      Css.color(Css.red),
      /* [] */0
    ]);

var p = Css.style(/* :: */[
      Css.color(Css.black),
      /* [] */0
    ]);

var date = Css.style(/* :: */[
      Css.color(Css.darkgray),
      /* [] */0
    ]);

var Styles = /* module */[
  /* article */article,
  /* link */link,
  /* h2 */h2,
  /* p */p,
  /* date */date
];

function Post(Props) {
  var post = Props.post;
  return React.createElement("article", {
              className: article
            }, React.createElement(Gatsby.Link, {
                  to: "/blog/" + post.frontmatter.path,
                  className: link,
                  children: React.createElement("h2", {
                        className: h2
                      }, post.frontmatter.title)
                }), React.createElement("p", {
                  className: p
                }, post.excerpt), React.createElement("small", {
                  className: date
                }, Utils$ReactTemplate.formatDate(post.frontmatter.date)));
}

var make = Post;

exports.str = str;
exports.Styles = Styles;
exports.make = make;
/* article Not a pure module */
