// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Gatsby = require("gatsby");
var Utils$ReactTemplate = require("./Utils.bs.js");

function str(prim) {
  return prim;
}

var article = Curry._1(Css.style, /* :: */[
      Css.marginBottom(Css.px(32)),
      /* [] */0
    ]);

var link = Curry._1(Css.style, /* :: */[
      Css.textDecoration(/* none */-922086728),
      /* :: */[
        Css.hover(/* :: */[
              Css.textDecoration(/* underline */131142924),
              /* :: */[
                Css.textDecorationColor(Css.red),
                /* [] */0
              ]
            ]),
        /* [] */0
      ]
    ]);

var h2 = Curry._1(Css.style, /* :: */[
      Css.color(Css.red),
      /* [] */0
    ]);

var p = Curry._1(Css.style, /* :: */[
      Css.color(Css.black),
      /* [] */0
    ]);

var date = Curry._1(Css.style, /* :: */[
      Css.color(Css.darkgray),
      /* [] */0
    ]);

var Styles = {
  article: article,
  link: link,
  h2: h2,
  p: p,
  date: date
};

function Post(Props) {
  var post = Props.post;
  return React.createElement("article", {
              className: article
            }, React.createElement(Gatsby.Link, {
                  to: "/blog/" + post.frontmatter.path,
                  className: link,
                  children: React.createElement("h2", {
                        className: h2
                      }, post.frontmatter.title)
                }), React.createElement("p", {
                  className: p
                }, post.excerpt), React.createElement("small", {
                  className: date
                }, Utils$ReactTemplate.formatDate(post.frontmatter.date)));
}

var make = Post;

exports.str = str;
exports.Styles = Styles;
exports.make = make;
/* article Not a pure module */
