// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReactTemplate = require("./Utils.bs.js");
var Gatsby$ReactTemplate = require("./types/Gatsby.bs.js");

function str(prim) {
  return prim;
}

var article = Css.style(/* :: */[
      Css.marginBottom(Css.px(32)),
      /* [] */0
    ]);

var link = Css.style(/* :: */[
      Css.textDecoration(/* none */-922086728),
      /* :: */[
        Css.hover(/* :: */[
              Css.textDecoration(/* underline */131142924),
              /* :: */[
                Css.textDecorationColor(Css.red),
                /* [] */0
              ]
            ]),
        /* [] */0
      ]
    ]);

var h2 = Css.style(/* :: */[
      Css.color(Css.red),
      /* [] */0
    ]);

var p = Css.style(/* :: */[
      Css.color(Css.black),
      /* [] */0
    ]);

var date = Css.style(/* :: */[
      Css.color(Css.darkgray),
      /* [] */0
    ]);

var Styles = /* module */[
  /* article */article,
  /* link */link,
  /* h2 */h2,
  /* p */p,
  /* date */date
];

var component = ReasonReact.statelessComponent("Post");

function make(post, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("article", {
                          className: article
                        }, ReasonReact.element(undefined, undefined, Gatsby$ReactTemplate.Link[/* make */0]("/blog/" + post.frontmatter.path, link, /* array */[React.createElement("h2", {
                                        className: h2
                                      }, post.frontmatter.title)])), React.createElement("p", {
                              className: p
                            }, post.excerpt), React.createElement("small", {
                              className: date
                            }, Utils$ReactTemplate.formatDate(post.frontmatter.date)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.str = str;
exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* article Not a pure module */
